name: Generate Auto PR

on:
  push:
    branches:
      - development
      - stage
      - main

jobs:
  call-auto-pr:
    permissions:
      contents: write
      pull-requests: write

    uses: tspyder7/github-actions-lib/.github/workflows/auto-pr.yml@feature/auto-pr-workflow
    with:
      pr-branch-hierarchy-json: |
        {
          "release": [
              "main"
          ],
          "main": [
              "stage"
          ],
          "stage": [
              "development"
          ]
        }
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
