name: Generate Auto PR

on:
  push:
    branches:
      - development
      - stage
      - main

jobs:
  call-auto-pr:
    permissions:
      contents: write
      pull-requests: write

    uses: tspyder7/github-actions-lib/.github/workflows/auto-pr.yml@ci/auto-pr-optimze-logging
    with:
      pr-branch-hierarchy-json: |
        {
          "main": [
              "development"
          ]
        }
    secrets:
      GH_TOKEN: ${{ secrets.GH_REPO_TOKEN  }}
