name: pr-hierarchy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  enforce-pr-hierarchy:
    permissions:
      contents: write
      pull-requests: write

    uses: tspyder7/github-actions-lib/.github/workflows/enforce-pr-hierarchy.yml@main
    with:
      allowed-branches-hierarchy-json: |
        {
            "release": [
                "main", "test"
            ],
            "main": [
                "stage", "test"
            ],
            "stage": [
                "development", "test"
            ]
        }

      comment-template: |
        🚫 **PR Automatically Closed - Branch Hierarchy Violation**

        **Issue**: This pull request violates the configured branch hierarchy rules.

        *This action was performed automatically by the branch hierarchy enforcement workflow.*


    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
