name: pr-hierarchy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  enforce-pr-hierarchy:
    permissions:
      contents: write
      pull-requests: write
    uses: tspyder7/github-actions-lib/.github/workflows/enforce-pr-hierarchy.yml@feature/enforce-pr-hierarchy-workflow
    with:
      allowed-branches-hierarchy-json: |
        {
            "release": [
                "main"
            ],
            "main": [
                "stage"
            ],
            "stage": [
                "development"
            ]
        }
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
